-- ==========================================================
-- [바이브 카페 (Vibe Cafe) - Supabase SQL Editor용 스크립트]
-- ==========================================================
-- Supabase 대시보드 > SQL Editor에 복사하여 [RUN] 버튼을 누르면
-- 테이블 생성부터 테스트 데이터(가짜 데이터 1건) 삽입까지 한 번에 완료됩니다.

-- 1. 기존 테이블이 있을 경우 삭제 (선택 사항, 필요 시 주석 해제)
-- DROP TABLE IF EXISTS cafe_orders;
-- DROP TABLE IF EXISTS cafe_menu;

-- ----------------------------------------------------------
-- 2-A. [주문서 항목 테이블] cafe_orders (주문 접수 데이터 저장용)
-- 주문서의 7가지 입력 항목 및 계산 금액, 상태, 생성시간을 모두 포함합니다.
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS cafe_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 주문 고유 번호 (PK)
    customer_name TEXT NOT NULL,                           -- 1. 이름 (필수)
    phone TEXT,                                            -- 2. 전화번호
    beverage TEXT NOT NULL,                                -- 3. 음료 선택 (아메리카노, 카페라떼 등)
    size VARCHAR(10) NOT NULL DEFAULT 'M',                 -- 4. 사이즈 (S, M, L)
    options TEXT[] DEFAULT '{}',                           -- 5. 추가 옵션 배열 (예: ['샷 추가', '크림 추가'])
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 1 AND quantity <= 10), -- 6. 수량 (1~10)
    requests TEXT,                                         -- 7. 요청사항
    total_price INTEGER NOT NULL CHECK (total_price >= 0), -- 실시간 계산된 총 금액
    status VARCHAR(20) DEFAULT '접수완료',                  -- 주문 상태 ('접수완료', '제조중', '제조완료', '수령완료')
    created_at TIMESTAMPTZ DEFAULT NOW()                   -- 주문 일시
);

-- RLS (Row Level Security) 설정: 익명 사용자도 주문서 등록(INSERT) 및 조회가 가능하도록 허용
ALTER TABLE cafe_orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "누구나 주문 등록 가능" ON cafe_orders;
CREATE POLICY "누구나 주문 등록 가능" ON cafe_orders
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "누구나 주문 내역 조회 가능" ON cafe_orders;
CREATE POLICY "누구나 주문 내역 조회 가능" ON cafe_orders
    FOR SELECT USING (true);


-- ----------------------------------------------------------
-- 2-B. [프롬프트 요청 대응] cafe_menu 테이블
-- (사용자 프롬프트에서 'cafe_menu 테이블에 주문서 항목 컬럼 생성'을 명시한 경우 호환)
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS cafe_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 메뉴/주문 식별자
    customer_name TEXT,                                    -- 1. 이름
    phone TEXT,                                            -- 2. 전화번호
    beverage_name TEXT NOT NULL,                           -- 3. 음료명 (예: 카페라떼)
    size VARCHAR(10) DEFAULT 'M',                          -- 4. 사이즈 (S, M, L)
    options TEXT,                                          -- 5. 선택 옵션 (문자열 또는 쉼표 구분)
    quantity INTEGER DEFAULT 1,                            -- 6. 수량
    requests TEXT,                                         -- 7. 고객 요청사항
    total_price INTEGER,                                   -- 총 예상/결제 금액
    created_at TIMESTAMPTZ DEFAULT NOW()                   -- 등록일시
);

ALTER TABLE cafe_menu ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "cafe_menu 전체 접근 허용" ON cafe_menu;
CREATE POLICY "cafe_menu 전체 접근 허용" ON cafe_menu
    FOR ALL USING (true) WITH CHECK (true);


-- ----------------------------------------------------------
-- 3. 테스트용 가짜 데이터 (Mock Data) 1건 INSERT 쿼리문
-- 주문서 요구사항 예시: 홍길동님, 카페라떼 M사이즈 (샷 추가) 1잔, 총 5,000원
-- ----------------------------------------------------------

-- [cafe_orders 테이블용 INSERT]
INSERT INTO cafe_orders (
    customer_name,
    phone,
    beverage,
    size,
    options,
    quantity,
    requests,
    total_price,
    status
) VALUES (
    '홍길동',
    '010-1234-5678',
    '카페라떼',
    'M',
    ARRAY['샷 추가'],
    1,
    '얼음 적게, 우유 따뜻하게 부탁드립니다 ☕',
    5000,
    '접수완료'
);

-- [cafe_menu 테이블용 INSERT (사용자 요청 명칭)]
INSERT INTO cafe_menu (
    customer_name,
    phone,
    beverage_name,
    size,
    options,
    quantity,
    requests,
    total_price
) VALUES (
    '홍길동',
    '010-1234-5678',
    '카페라떼',
    'M',
    '샷 추가 (+500원)',
    1,
    '얼음 적게 부탁드립니다.',
    5000
);

-- ----------------------------------------------------------
-- 4. 등록 결과 확인용 SELECT
-- ----------------------------------------------------------
SELECT * FROM cafe_orders ORDER BY id DESC LIMIT 1;
