import React, { useState } from 'react';
import { Database, Copy, Check, X, Terminal, ExternalLink } from 'lucide-react';

interface SupabaseModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const SupabaseModal: React.FC<SupabaseModalProps> = ({ isOpen, onClose }) => {
  const [copiedType, setCopiedType] = useState<string | null>(null);

  if (!isOpen) return null;

  // 전체 통합 SQL 스크립트 (테이블 생성 + 가짜 데이터 INSERT)
  const fullSqlScript = `-- ==========================================================
-- [바이브 카페 (Vibe Cafe) - Supabase SQL Editor 실행 쿼리]
-- Supabase 대시보드 > SQL Editor에 복사 후 'Run'을 누르세요.
-- ==========================================================

-- 1. [주문서 항목 테이블] cafe_orders 생성
CREATE TABLE IF NOT EXISTS cafe_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 고유 식별자 (PK)
    customer_name TEXT NOT NULL,                           -- 1. 이름 (필수)
    phone TEXT,                                            -- 2. 전화번호
    beverage TEXT NOT NULL,                                -- 3. 음료명 (아메리카노, 카페라떼 등)
    size VARCHAR(10) NOT NULL DEFAULT 'M',                 -- 4. 사이즈 (S, M, L)
    options TEXT[] DEFAULT '{}',                           -- 5. 추가 옵션 배열
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 1 AND quantity <= 10), -- 6. 수량
    requests TEXT,                                         -- 7. 요청사항
    total_price INTEGER NOT NULL,                          -- 실시간 계산 총 금액
    status VARCHAR(20) DEFAULT '접수완료',                  -- 상태 ('접수완료', '제조중', '제조완료')
    created_at TIMESTAMPTZ DEFAULT NOW()                   -- 접수 일시
);

-- RLS (행 수준 보안) 활성화 및 누구나 등록/조회 가능 정책
ALTER TABLE cafe_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "누구나 주문 등록 가능" ON cafe_orders
    FOR INSERT WITH CHECK (true);

CREATE POLICY "누구나 주문 내역 조회 가능" ON cafe_orders
    FOR SELECT USING (true);


-- 2. [가짜 데이터 1건 INSERT 쿼리문]
-- 홍길동님, 카페라떼 M사이즈 (샷 추가) 1잔, 총 5,000원
INSERT INTO cafe_orders (
    customer_name,
    phone,
    beverage,
    size,
    options,
    quantity,
    requests,
    total_price,
    status
) VALUES (
    '홍길동',
    '010-1234-5678',
    '카페라떼',
    'M',
    ARRAY['샷 추가'],
    1,
    '얼음 적게 부탁드립니다.',
    5000,
    '접수완료'
);

-- 3. 확인용 조회 쿼리
SELECT * FROM cafe_orders ORDER BY id DESC LIMIT 1;`;

  // 단독 테이블 생성 쿼리
  const createTableSql = `CREATE TABLE IF NOT EXISTS cafe_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    phone TEXT,
    beverage TEXT NOT NULL,
    size VARCHAR(10) NOT NULL DEFAULT 'M',
    options TEXT[] DEFAULT '{}',
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 1 AND quantity <= 10),
    requests TEXT,
    total_price INTEGER NOT NULL,
    status VARCHAR(20) DEFAULT '접수완료',
    created_at TIMESTAMPTZ DEFAULT NOW()
);`;

  // 단독 테스트 데이터 INSERT 쿼리
  const insertMockSql = `INSERT INTO cafe_orders (
    customer_name, phone, beverage, size, options, quantity, requests, total_price, status
) VALUES (
    '홍길동', '010-1234-5678', '카페라떼', 'M', ARRAY['샷 추가'], 1, '얼음 적게 부탁드립니다.', 5000, '접수완료'
);`;

  const copyToClipboard = (text: string, type: string) => {
    navigator.clipboard.writeText(text);
    setCopiedType(type);
    setTimeout(() => setCopiedType(null), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-xs">
      <div className="bg-[#ffffff] rounded-2xl shadow-2xl border border-[#d4c3b3] w-full max-w-[560px] max-h-[90vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        
        {/* 모달 상단 헤더 */}
        <div className="px-6 py-4 bg-[#6b4226] text-white flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-1.5 bg-[#835231] rounded-lg">
              <Database className="w-5 h-5 text-[#fbf7f2]" />
            </div>
            <div>
              <h2 className="text-lg font-bold">Supabase SQL Editor 쿼리문</h2>
              <p className="text-xs text-[#eedfd2]">바이브 카페 주문서 테이블 및 테스트 데이터</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-[#eedfd2] hover:text-white hover:bg-[#835231] transition-colors"
            aria-label="닫기"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* 모달 본문 */}
        <div className="p-6 overflow-y-auto space-y-5 text-sm">
          {/* 사용 방법 안내 */}
          <div className="p-3.5 bg-[#faf6f0] rounded-xl border border-[#d4c3b3]/60 text-[#4a3627]">
            <p className="font-semibold mb-1 flex items-center gap-1.5 text-xs text-[#6b4226]">
              <Terminal className="w-4 h-4" /> Supabase 적용 방법
            </p>
            <ol className="list-decimal list-inside text-xs space-y-1 text-[#6b5849]">
              <li>Supabase 프로젝트 대시보드에 접속합니다.</li>
              <li>좌측 사이드바에서 <strong>SQL Editor</strong> 메뉴를 클릭합니다.</li>
              <li>아래 <strong>[전체 쿼리 복사]</strong> 버튼을 누른 뒤 에디터에 붙여넣습니다.</li>
              <li>우측 하단의 초록색 <strong>[Run]</strong> 버튼을 누르면 즉시 생성됩니다.</li>
            </ol>
          </div>

          {/* 1. 테이블 생성 쿼리 섹션 */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <span className="font-bold text-[#6b4226] flex items-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-[#6b4226]"></span>
                1. cafe_orders 테이블 생성 SQL
              </span>
              <button
                onClick={() => copyToClipboard(createTableSql, 'create')}
                className="inline-flex items-center gap-1 px-2.5 py-1 text-xs rounded-md bg-[#faf6f0] border border-[#d4c3b3] text-[#6b4226] hover:bg-[#eadecf] font-medium transition-colors cursor-pointer"
              >
                {copiedType === 'create' ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5" />}
                {copiedType === 'create' ? '복사됨!' : '테이블 SQL 복사'}
              </button>
            </div>
            <pre className="bg-[#2a221b] text-[#e8ded5] p-3.5 rounded-xl text-xs overflow-x-auto font-mono leading-relaxed border border-[#3e3228]">
              {createTableSql}
            </pre>
          </div>

          {/* 2. 가짜 데이터 1건 INSERT 쿼리 섹션 */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <span className="font-bold text-[#6b4226] flex items-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-[#6b4226]"></span>
                2. 테스트용 가짜 데이터 (1건) INSERT SQL
              </span>
              <button
                onClick={() => copyToClipboard(insertMockSql, 'insert')}
                className="inline-flex items-center gap-1 px-2.5 py-1 text-xs rounded-md bg-[#faf6f0] border border-[#d4c3b3] text-[#6b4226] hover:bg-[#eadecf] font-medium transition-colors cursor-pointer"
              >
                {copiedType === 'insert' ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5" />}
                {copiedType === 'insert' ? '복사됨!' : 'INSERT SQL 복사'}
              </button>
            </div>
            <pre className="bg-[#2a221b] text-[#e8ded5] p-3.5 rounded-xl text-xs overflow-x-auto font-mono leading-relaxed border border-[#3e3228]">
              {insertMockSql}
            </pre>
            <p className="mt-1 text-xs text-[#827163]">
              ※ 홍길동님, 카페라떼 M (샷 추가) 1잔, 총 5,000원 주문 기준
            </p>
          </div>

          {/* 컬럼 매핑 테이블 안내 */}
          <div className="bg-[#faf6f0] p-3 rounded-xl border border-[#d4c3b3]/60">
            <span className="text-xs font-semibold text-[#6b4226] block mb-1.5">주문서 항목 ↔ DB 컬럼 매핑</span>
            <div className="grid grid-cols-2 gap-x-2 gap-y-1 text-[11px] text-[#5c4a3b]">
              <div>• 1. 이름 : <code>customer_name</code></div>
              <div>• 2. 전화번호 : <code>phone</code></div>
              <div>• 3. 음료 선택 : <code>beverage</code></div>
              <div>• 4. 사이즈 : <code>size</code></div>
              <div>• 5. 추가 옵션 : <code>options (배열)</code></div>
              <div>• 6. 수량 : <code>quantity</code></div>
              <div>• 7. 요청사항 : <code>requests</code></div>
              <div>• 총 예상금액 : <code>total_price</code></div>
            </div>
          </div>
        </div>

        {/* 모달 하단 버튼 영역 */}
        <div className="px-6 py-3.5 bg-[#faf6f0] border-t border-[#d4c3b3] flex items-center justify-between">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-medium text-[#6b4226] hover:bg-[#eadecf] rounded-lg transition-colors cursor-pointer"
          >
            닫기
          </button>
          <button
            onClick={() => copyToClipboard(fullSqlScript, 'all')}
            className="inline-flex items-center gap-1.5 px-4 py-2 text-xs font-bold text-white bg-[#6b4226] hover:bg-[#7f4f2f] rounded-lg transition-all shadow-sm cursor-pointer"
          >
            {copiedType === 'all' ? <Check className="w-4 h-4 text-green-300" /> : <Copy className="w-4 h-4" />}
            {copiedType === 'all' ? '전체 SQL 복사 완료!' : '전체 SQL 스크립트 복사'}
          </button>
        </div>

      </div>
    </div>
  );
};
